### ISSUE TITLE
Tagging releases known to work with parent module

### ISSUE THREAD

**Issue by ehaupt** [trezor/trezor-common#129]
Now that this submodule is required for 'python-trezor' could you please tag versions that are known to work with 'python-trezor'. This would tremendously help the packaging effort of the various projects:

https://repology.org/metapackage/python:trezor/versions

Thanks in advance :-)

**Comment by prusnak** [comment]
I don't get it. Commit which is included as a submodule to python-trezor should work. If you are packaging python-trezor to a distribution, you should use the exact commit, as can be seen here for example: https://github.com/trezor/python-trezor/tree/v0.10.0/vendor

**Comment by ehaupt** [comment]
In the ports framework I have to specify sub modules seperately. For now I've specified the last commit hash. It would be better if you could tag (or version) the sub modules as well.

**Comment by prusnak** [comment]
@matejcik What do you think? Is it worth the effort and extra tags in trezor-common?

**Comment by matejcik** [comment]
Uhhh specifying submodules separately is basically like not using them in the first place? o_O
That just seems like bad design to me. I mean ... the information you want is already in the python-trezor repository, you can use `git submodule status` to extract it. Otherwise the dependency graph goes the wrong way; as it is, trezor-common doesn't (and shouldn't need to) know about python-trezor.
Also this creates an opportunity for mistakes - if we fail to sync the tags, we can end up with mismatched versions.

All in all i'm not too happy about adding this, esp. given that trezor-common currently doesn't have a versioning scheme.

@ehaupt Is there a reason you can't set up a script to extract and use the appropriate hash from the git script?

**Comment by ehaupt** [comment]
It's not about building this locally on some box. It's to ensure we have static FreeBSD packages.

In the FreeBSD ports framework sources are fetched via HTTPS (not via git) based on tags/releases (the same you're receiving when clicking the .tar.gz link under the tagged releases tab). The fetched tarballs are then checked against a recorded SHA256 checksum to verify its integrity.

Right now I am just using the alphanumeric git commit hash to reference the latest version I've verified to work in order to fetch sources and I will continue to do so if it's too much hassle for you to version the sources.

This is the FreeBSD port:
https://svnweb.freebsd.org/ports/head/security/py-trezor/

**Comment by matejcik** [comment]
But you could fetch the appropriate submodule commit hash at the same step where you update the version and fingerprints of the tarballs, right? It seems easier than manually verifying whether the latest commit is working properly. GitHub API even [exposes this](https://developer.github.com/v3/repos/contents/#get-contents).

Maybe it would be cleaner to use PyPI releases instead? The source tarball there (output of `python setup.py sdist`) is self-contained, and you'd be getting the same thing all pypi users are getting.

Anyway, we will not be adding such tags at this time. But I'll keep this in mind in case we start versioning trezor-common.

**Comment by ehaupt** [comment]
Yes in this case I'll move to the PyPI releases. Again I can't use any API calls during the fetch process as the FreeBSD ports framework requires a static URL for the sources to be fetched.
